# Copyright (c) 2013-2018 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the License); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Notes:
# - How to use YAML multilines: https://yaml-multiline.info/

language: bash

cache:
  branch: bash
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/.cache/choco
    - ${HOME}/.cache/compilers

env:
  global:
    - deps_url="https://s3-eu-west-1.amazonaws.com/mbed-os/deps"
    - gcc6_path="${HOME}/.cache/compilers/gcc-arm-none-eabi-6-2017-q2-update"
    - gcc7_path="${HOME}/.cache/compilers/gcc-arm-none-eabi-7-2018-q2-update"
    - gcc8_path="${HOME}/.cache/compilers/gcc-arm-none-eabi-8-2018-q4-major"
    - compile_k64f="mbed test --compile -m K64F -t GCC_ARM"
    - long_dir="this_is_a_rather_long_directory_name"
    - really_long_dir="this_is_an_even_longer_directory_name_that_will_probably_cause_things_to_fail"

install:
### Setup GCC ###
  - source tools/test/travis-ci/functions.sh
  - source_gcc "${gcc_path}" "${gcc_archive_name}"
  - ${gcc_path}/bin/arm-none-eabi-gcc --version


### Setup Python ###
  - python --version
  # Update python install tools
  - python -m pip install --upgrade pip==18.1
  - python -m pip install --upgrade setuptools==40.4.3
  # Install required modules
  - |-
    tr -d ' ' >> requirements.txt <<< "
    mock==2.0.0
    pytest==3.3.0
    pylint>=1.9,<2
    hypothesis>=3,<4
    coverage>=4.5,<5
    coveralls>=1.5,<2
    "
  - pip install -r requirements.txt --cache-dir ${HOME}/.cache/pip
  - pip list --verbose

### Setup Mbed CLI ###
  - pip install mbed-cli
  - mbed --version

script:
### Test Python ###
  #- PYTHONPATH=. coverage run -a -m pytest tools/test
  #- python tools/test/pylint.py
  #- coverage run -a tools/project.py -S | sed -n '/^Total/p'
  #- coverage html

### Test Compile ###
  - mbed config --global GCC_ARM_PATH "${gcc_path}/bin"
  - |+
    (
      cd ../
      mkdir -p "${long_dir}/mbed-os"
      cp -r mbed-os/* "${long_dir}/mbed-os/"
    )
    #  - |+
    #    pwd
    #    ${compile_k64f} --stats-depth=0 --clean &> compile.log \
    #      || ${compile_k64f} --verbose 2>&1 &
    #    pid=$!
    #    while kill -s 0 "${pid}" 2> /dev/null; do
    #      < compile.log tail -n1
    #      sleep 60
    #    done
  - |+
    (
      cd "../${long_dir}/mbed-os"
      pwd
      ${compile_k64f} -n features-storage-filesystem-littlefs-* --clean -vv 2>&1
    )



matrix:
  include:

    - &linux-vm
      name: linux.gcc6.py27
      os: linux
      env: gcc_path="${gcc6_path}" gcc_archive_name="gcc6-linux.tar.bz2"
      dist: xenial
      python: 2.7
      language: python

    - <<: *linux-vm
      name: linux.gcc6.py37
      python: 3.7

    - &windows-vm
      name: windows.gcc6.py27
      os: windows
      env: py_ver=2.7.15 py_pkg_name=python2 py_path="/c/Python27" gcc_path="${gcc6_path}" gcc_archive_name="gcc6-win.zip"
      before_install:
        - choco config set cacheLocation ${HOME}/.cache/choco
        - choco install ${py_pkg_name} --version ${py_ver}
        - export "PATH=${py_path}:${py_path}/Scripts/:${PATH}"

    - <<: *windows-vm
      name: windows.gcc6.py37
      env: py_ver=3.7.2 py_pkg_name=python3 py_path="/c/Python37" gcc_path="${gcc6_path}" gcc_archive_name="gcc6-win.zip"


    - <<: *windows-vm
      name: windows.gcc7.py27
      env: py_ver=2.7.15 py_pkg_name=python2 py_path="/c/Python27" gcc_path="${gcc7_path}" gcc_archive_name="gcc7-win.zip"
    - <<: *windows-vm
      name: windows.gcc7.py37
      env: py_ver=3.7.2 py_pkg_name=python3 py_path="/c/Python37" gcc_path="${gcc7_path}" gcc_archive_name="gcc7-win.zip"

    - <<: *windows-vm
      name: windows.gcc8.py27
      env: py_ver=2.7.15 py_pkg_name=python2 py_path="/c/Python27" gcc_path="${gcc8_path}" gcc_archive_name="gcc8-win.zip"
    - <<: *windows-vm
      name: windows.gcc8.py37
      env: py_ver=3.7.2 py_pkg_name=python3 py_path="/c/Python37" gcc_path="${gcc8_path}" gcc_archive_name="gcc8-win.zip"

